name: saferide_ai_app
description: "An advanced AI-powered vehicle monitoring system for comprehensive driver and passenger safety. Features include drowsiness detection, distraction monitoring, motion sickness detection, yawning analysis, and erratic movement detection - designed for in-car installation."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.0
  video_player: ^2.8.2
  google_mlkit_face_detection: ^0.13.1
  provider: ^6.0.0
  permission_handler: ^12.0.1
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.15
  wakelock_plus: ^1.1.1
  path_provider: ^2.0.11
  path: ^1.8.2
  flutter_local_notifications: ^19.4.0
  vibration: ^3.1.3
  flutter_tts: ^4.0.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  network_info_plus: ^6.0.0
  # Cloud streaming dependencies
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.2
  firebase_database: ^11.1.4
  cloud_firestore: ^5.4.3
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  uuid: ^4.5.1
  # Analytics and charts
  fl_chart: ^0.69.0
  # Additional UI improvements
  table_calendar: ^3.1.2
  url_launcher: ^6.3.1
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
